### ISSUE TITLE
can we directly have the map inside our app without passing url??

### ISSUE THREAD

**Issue by Pattyx** [coronalabs/samples-coronasdk#3]

**Comment by Pattyx** [comment]
if on click button i dont want to take it google map

**Comment by coronarob** [comment]
Which sample app are you looking at?

**Comment by Pattyx** [comment]
i want to make an app which can take location of a user using gps and show
mapview as well in that app

**Comment by coronarob** [comment]
Hi Pattyx. You're posting comments on a source code repository for Corona's sample apps. You don't seem to be asking a question about the code in a sample app or reporting a bug. This is not our community forums where you should ask questions like this. You should be asking this at https://forums.coronalabs.com

You could also look on our documentation site: https://docs.coronalabs.com and look at the native.newMapView() API call (https://docs.coronalabs.com/api/library/native/newMapView.html)

Please continue converstions about this topic on the community forums!
